### ISSUE TITLE
Could you share all the models for your reproducted baseline

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [nileshkulkarni/relative3d#6]
Hello, Nil, Could you share all the models for the results on the table? Specifically, for your reproducted baseline results. I tried to use batch size 24 for baseline reproduction,  but can not reproduct your factored3d result. From your link [here](https://www.dropbox.com/s/r7xw5fw6awj5h4v/cachedir.tar.gz?dl=0) (now is broken), I can only obtain the following model.
`
box3d_base_spatial_mask_common_upsample/  
dwr_base_spatial_mask_common_upsample/  
layout_pred/  nyu_relnet_dwr_pos_ft/  
object_autoenc_32/  
pretrained_dwr_shape_ft/  
suncg_relnet_dwr_pos_ft/
`
However, from your baseline guideline [here](https://github.com/nileshkulkarni/relative3d/blob/master/docs/baselines.md), your reproducted baseline models are
`
box3d_base_factored3d_baseline, 
dwr_base_factored3d_baseline_ft, 
box3d_base_factored3d_baseline_nyu, 
dwr_base_factored3d_baseline_nyu
`
which are missing.

**Comment by KnightOfTheMoonlight** [comment]
There is a large performance difference from your reproduction and the model 
 from original factored3d `pretrained_dwr_shape_ft`, you provide this model in your [cachedir](https://www.dropbox.com/s/r7xw5fw6awj5h4v/cachedir.tar.gz?dl=0).

**Comment by nileshkulkarni** [comment]
Hi,

The model "pretrained_dwr_shape_ft" is only used to get detections scores for evaluating all the models in a fair comparison setting. As computing mAP depends on the detection scores. 

The results reported in the paper for the baseline are from a model trained using the code provided. The "pretriained_dwr_shape_ft" model is not trained using this codebase. There were several changes I had to do make the baseline code faster, including changing the roi_pool implementation, and the base rotation clusters might also be different. So, I would not expect it to match the results exactly. 

Best,
Nilesh

**Comment by KnightOfTheMoonlight** [comment]
Hi, Nilesh, so, in summary, you change proposal generation and batch size setting. Then could you share your pretrained models? And besides, your link is not available, could you fix it? Thanks!

**Comment by nileshkulkarni** [comment]
Hi,

Here is the baseline model I found from my codebase that was used to report the results in the paper.  Since the current code base is new, please follow the following instructions to make it compatible with the baseline model. Note you can use the same model to get numbers in the gt box setting and the detection setting. I'm highlighting instructions to get them in detection setting.

Since the model might not be completely compatible, we have to make a few changes to the load_network function in test_utils. Please add strict=False. Should look like this.
![image](https://user-images.githubusercontent.com/2604793/65113001-67790780-d9af-11e9-837c-7df7718acde5.png)


1. Download the model from [here](https://cmu.box.com/s/2d58ibyl4mo2o5n7nr4pm2jzd7l2md7g)
2. Uncomment [lines](https://github.com/nileshkulkarni/relative3d/blob/427a4a9381504fd20d928084f1a446bd8feaeb68/benchmark/suncg/dwr.py#L135-L136
). L134, L135 in benchmark/suncg/dwr.py 
3. Run this to evaluate the detection scores 
`python -m relative3d.benchmark.suncg.dwr --num_train_epoch=1 --name=factored3d_pos_ft_baseline  --classify_rot --pred_voxels=True --use_context   --eval_set=val --suncg_dir=/nfs.yoda/nileshk/suncg/ --use_spatial_map=False --pos_label_model
`
I hope this helps.

Best,
Nilesh
